# Generated by Django 5.1.1 on 2024-09-05 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0003_profile_specializedservices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
        migrations.AddField(
            model_name='organization',
            name='industry',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='profileId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERS.profile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='size',
            field=models.CharField(choices=[('home', 'Home'), ('Sm Ent', 'Small Enterprice'), ('Lg Ent', 'Large Enterprice')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
