# Generated by Django 5.1.1 on 2024-09-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0004_remove_customuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
