# Generated by Django 5.1.1 on 2024-09-06 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0005_organization_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profileID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='USERS.profile'),
        ),
    ]
