# Generated by Django 5.1.1 on 2024-09-06 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0006_alter_customuser_profileid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='profileID',
            new_name='profile',
        ),
    ]
