# Generated by Django 5.1.1 on 2024-09-06 06:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('USERS', '0007_rename_profileid_customuser_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='profileId',
            new_name='profile',
        ),
    ]
